name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.0.2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0
        with:
          working-directory: ./frontend

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Copy frontend files to webserver folder
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: frontend/build/*
          target: "/var/www/${{ secrets.DOMAIN }}"
          strip_components: 1
