name: Build and Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show build files (before)
        run: ls ${{github.workspace}}
        
      - name: Clean Install to Include all Dependencies
        run: npm ci
        
      - name: Build Project
        run: npm run build
        
      - name: Show product
        run: ls ${{github.workspace}}/dist
        
      - name: Copy to webserver folder
        run: scp -r ${{github.workspace}}/dist/* nexus@dev.misfits.rip:/var/www/dev.misfits.rip
        
