name: Build, Test and Transfer

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.0.2

      - name: Install Node Deps
        uses: bahmutov/npm-install@v1.10.2
        with:
          working-directory: ./frontend

      - name: NPM Run Build (Vite)
        working-directory: ./frontend
        run: npm run build
      #run tests here eventually

      - name: SCP Build Artifact to AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build,frontend/package.json,frontend/package-lock.json"
          target: "~/${{ secrets.DOMAIN }}"
          rm: true
          strip_components: 2
