name: Build and Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Build Project
        run: npm run build
        
      - name: Copy to webserver folder
        run: scp -r .dist/* nexus@dev.misfits.rip:/var/www/dev.misfits.rip/
        
